### ISSUE TITLE
App not deployed and Siddhi-Operator goes down if @App:name contains single quotes

### ISSUE THREAD

**Issue by LakshanSS** [siddhi-io/siddhi-operator#17]
**Description:**
If the @App:name annotation in  SiddhiProcess YAML file contains single quotes, deployment is not created for the app and the siddhi-operator goes down. siddhi-operator pod is restarted again and again, but it doesn't come back to normal.

Example: `@App:name('ShipmentHistoryApp')`

**Affected Product Version:**
siddhi-operator 0.1.1

**OS, DB, other environment details and versions:**    
Minikube v1.1.1
kubectl v1.14.3

**Comment by BuddhiWathsala** [comment]
From the YAML file that you were given siddhi operator gets the siddhi app as a string. Since siddhi operator doesn't have a language parser to parse the siddhi query language, siddhi operator use a regex to extract the siddhi app name from given siddhi app.

That regex currently supports only for the names that have double quotes as below. So you can change the siddhi app name like this.
```
@app:name("ShipmentHistoryApp")
```
In the next release, we will fix this issue.

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-operator/pull/34 by Buddhi..
