### ISSUE TITLE
Siddhi-operator pod logs contain developer's paths

### ISSUE THREAD

**Issue by LakshanSS** [siddhi-io/siddhi-operator#18]
**Description:**
Logs of the siddhi-operator pod contain developer's paths

**Screenshot**
![Screenshot from 2019-06-12 11-40-13](https://user-images.githubusercontent.com/32201965/59327512-5dd46980-8d07-11e9-8fc8-2d26f5d842a1.png)

**Affected Product Version:**
siddhi-operator 0.1.1

**Comment by BuddhiWathsala** [comment]
Siddhi operator uses [operator-sdk](https://github.com/operator-framework/operator-sdk) to build the kubernetes operator image. So this issue was actually related to [this operator sdk issue](https://github.com/operator-framework/operator-sdk/issues/1530).

Since operator sdk resolve this issue recently, we can fix this issue in our next release.

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-operator/pull/34 by Buddhi..
