### ISSUE TITLE
NATS support for Siddhi failover deployment

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/siddhi-operator#20]
**Description:**
Implementation to support NATS as the messaging system for Siddhi Fail-over deployment.

**Comment by BuddhiWathsala** [comment]
In the next failover support release of the siddhi-operator, will by default use [NATS streaming](https://github.com/nats-io/nats-streaming-operator) as the messaging layer. In order to use siddhi failover deployment installing [NATS streaming](https://github.com/nats-io/nats-streaming-operator) will be a prerequisite.

Here users can install NATS streaming clusters in the kubernetes cluster using [NATS streaming operator](https://github.com/nats-io/nats-streaming-operator).

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-operator/pull/34 by Buddhi..
